### ISSUE TITLE
[Game]ゲームのコンポーネントとルートのネストをなくす。

### ISSUE THREAD

**Issue by kny-i** [Shuta-syd/42-ft_transcendence#154]
## やること
- [ ] App.tsxにおいてgameが箇条書きになっている。これをそれぞれコンポーネント化してchatみたいにネスト状にする（ログインしてるしてないとかの制御を楽にするため）

**Comment by Jack-in-42Tokyo** [comment]
gameのroutingに関してもう一度mainからcheckoutして作り直す
