### ISSUE TITLE
【BUG】Gameに再度入り直すと正常にゲームが開始されないバグの解消

### ISSUE THREAD

**Issue by Shuta-syd** [Shuta-syd/42-ft_transcendence#166]
## 機能概要
Gameに再度入り直すと正常にゲームが開始されないバグの解消

**Comment by Jack-in-42Tokyo** [comment]
Gameの構造自体が変わるからissueとしては一旦取り下げていいかもしれない

**Comment by kny-i** [comment]
Gameは1から書き直しになったのでclose
https://github.com/Shuta-syd/42-ft_transcendence/issues/257 を確認
