### ISSUE TITLE
【Game】ゲームのランダムマッチを同じ条件（スピード、得点数）のみのユーザとマッチする仕様に変更

### ISSUE THREAD

**Issue by Shuta-syd** [Shuta-syd/42-ft_transcendence#185]
## 機能概要
ゲームのランダムマッチを同じ条件（スピード、得点数）のみのユーザとマッチする仕様に変更
→ player1に依存しない仕様に変更

**Comment by kny-i** [comment]
Gameは1から書き直しになったのでclose
https://github.com/Shuta-syd/42-ft_transcendence/issues/257 を確認
