### ISSUE TITLE
【Game】ゲーム参加者が揃った時点でカウントダウンを表示し、その後スタートする仕様に変更

### ISSUE THREAD

**Issue by Shuta-syd** [Shuta-syd/42-ft_transcendence#186]
## 機能概要
ゲーム参加者が揃った時点でカウントダウンを表示し、その後スタートする仕様に変更

**Comment by kny-i** [comment]
Gameは1から書き直しになったのでclose
https://github.com/Shuta-syd/42-ft_transcendence/issues/257 を確認
