### ISSUE TITLE
【Game】RECONNECT時にボールが真ん中に移り、ラグが発生するのを防ぐ

### ISSUE THREAD

**Issue by Shuta-syd** [Shuta-syd/42-ft_transcendence#187]
## 機能概要
RECONNECT時にボールが真ん中に移り、ラグが発生するのを防ぐ

現状RECONNECTボタンを押すと、一回ボールが真ん中に移動してしまう。

**Comment by kny-i** [comment]
Gameは1から書き直しになったのでclose
https://github.com/Shuta-syd/42-ft_transcendence/issues/257 を確認
