### ISSUE TITLE
フレンドIDを送信したことがわかるようにする

### ISSUE THREAD

**Issue by public-jun** [Shuta-syd/42-ft_transcendence#191]
フレンドIDを送信したら、フレンドID入力欄を空にして欲しい
![スクリーンショット 2023-03-30 0 05 34](https://user-images.githubusercontent.com/60804160/228582974-27235e48-59cb-40c0-b137-e5765d0a8d0e.png)

空にしなくても良いけど、送信したことがわかるようにして欲しい

**Comment by Jack-in-42Tokyo** [comment]
pull req時に修正
