### ISSUE TITLE
【Profile】プロフィール画面からフレンド機能操作フロント機能

### ISSUE THREAD

**Issue by public-jun** [Shuta-syd/42-ft_transcendence#200]
## 機能概要
・他のユーザーのプロフィールを覗いた時に、「フレンド申請」ボタンの設置。
・自分のプロフィールを覗いた時に、「フレンド申請一覧」ボタンの設置。

## やること
- [ ] 他のユーザーのプロフィールを覗いた時に、「フレンド申請」ボタンの設置。
- [ ] 自分のプロフィールを覗いた時に、「フレンド申請一覧」ボタンの設置。

**Comment by Jack-in-42Tokyo** [comment]
200だと要素として大きすぎたので、他のissueに移動
