### ISSUE TITLE
【Login】intra名が被ってしまった場合またはすでに同様のユーザネームが存在する場合のバグ解消

### ISSUE THREAD

**Issue by Shuta-syd** [Shuta-syd/42-ft_transcendence#215]
## 機能概要
intra名が被ってしまった場合またはすでに同様のユーザネームが存在する場合のバグ解消

**Comment by Shuta-syd** [comment]
buttonのhrefからコールバックでログインしているがこれをaxiosで叩けるようにしたい

1. 同じユーザ名がすでに存在していた場合、テキストフィールドを表示してユーザ名を変更してもらいたいが、そもそもhrefでコールバックしているため、値をバックエンドに送信できない。
2. バックエンド側で'already in use'の例外がthrowされたときに例外をキャッチできず、callbackでURLが止まる

**Comment by public-jun** [comment]
prefix suffixつける！

**Comment by Shuta-syd** [comment]
一旦情報のユニーク性を置いといてフロントに持ち帰って編集するのもありかなと思いましたが、そもそも情報をフロントに送れないことがボトルネックになってできなそうです、、

解決策思いついたと思ったんですが、、
