### ISSUE TITLE
【Profile】ログイン後プロフィール画面で画像、emailを編集可能にする

### ISSUE THREAD

**Issue by Shuta-syd** [Shuta-syd/42-ft_transcendence#218]
## 機能概要
ログイン後プロフィール画面でユーザーネーム、画像、emailを編集可能にする

**Comment by kny-i** [comment]
usernameとemailの変更はなしっていう話にならなかったけ？

**Comment by Shuta-syd** [comment]
必要でした！

サブジェットに明記されてました

**Comment by Jack-in-42Tokyo** [comment]
emailのみ変更する仕様に決定したので取り組む
emailはuniqueなので、既にemailが設定されていないかどうかをcheckしてから変更を加える
