### ISSUE TITLE
[Profile] followできるようにする

### ISSUE THREAD

**Issue by Jack-in-42Tokyo** [Shuta-syd/42-ft_transcendence#227]
## やること
- 他のuserのprofileに飛んだ時に、そこからfollowする
- 自分にfollowがきていないかどうかを確認して、きていた場合には通知を何らかの形で完治できるようにする
- 上の事項を実装するにあたって不要な部分の削除

**Comment by kny-i** [comment]
今回の場合はfollowってよりも、友達申請の方が近いと思う
 @Jack-in-42Tokyo

**Comment by Jack-in-42Tokyo** [comment]
通知をチェックして、accept or rejectの判断をuserにさせる

**Comment by Jack-in-42Tokyo** [comment]
_ここからの流れ_
フレンド申請が来てるuser idを見れるようになっているので、そのuser idからuser情報を取得してきて、nameを表示し、その横にaccept or reject buttonを出す。
↑そのbuttonそれぞれに対して、APIを叩かせる

**Comment by Jack-in-42Tokyo** [comment]
Accept/Declineまで実装に取り掛かってるけど、よく見たらissue分けても良かったかも。
完成しちゃいそうなんでそのままpull request出します
