### ISSUE TITLE
[Profile] on/offlineのstatusを正常に取れるようにdebugする

### ISSUE THREAD

**Issue by Jack-in-42Tokyo** [Shuta-syd/42-ft_transcendence#230]
## 機能概要
現状on/offlineのステータスがうまく確認することができていないので、debug、もしくはアルゴリズム改善をする必要がある

**Comment by Shuta-syd** [comment]
onlineステータスのgatewayを回収したのでProfileのUI他実装が終わった後に調整するのが良さそう

**Comment by public-jun** [comment]
@kny-i 
https://github.com/Shuta-syd/42-ft_transcendence/pull/269
このブランチの続きからよろしくお願いします！
