### ISSUE TITLE
【Game】socketリファクタリングによるゲームバグ解消

### ISSUE THREAD

**Issue by Shuta-syd** [Shuta-syd/42-ft_transcendence#243]
## 機能概要
socketリファクタリングによるゲームバグ解消。
socketのautoConntectオフによる弊害をコンポーネントを再実装することで解消する

**Comment by Shuta-syd** [comment]
@kny-i 
@Jack-in-42Tokyo 

#240 はソケットを取り替えただけだけどゲームが正常に動作しない（部屋の割り振りがおかしくなってる）からどこがおかしそうか教えてくれるとありがたい

**Comment by kny-i** [comment]
> @kny-i @Jack-in-42Tokyo
> 
> #240 はソケットを取り替えただけだけどゲームが正常に動作しない（部屋の割り振りがおかしくなってる）からどこがおかしそうか教えてくれるとありがたい

後でコードみてみる！
とはいえ、バックエンド化したらそこら辺も結構変わる気がするから、今直したとしてもそれは使用しないことになるかも。
