### ISSUE TITLE
[Profile]戦績一覧を表示する

### ISSUE THREAD

**Issue by Jack-in-42Tokyo** [Shuta-syd/42-ft_transcendence#251]
## 機能概要
Friend List Buttonと同じフォーマットで戦績一覧に関しても表示できるようにする

**Comment by Jack-in-42Tokyo** [comment]
既にフォーマットはできてるので、propsから渡しさえすれば完成予定

**Comment by public-jun** [comment]
ハルくんがコメントアウトを外したら、完成予定
