### ISSUE TITLE
[Chat]User Participantsで名前が被ってしまうので修正した方が良さそう

### ISSUE THREAD

**Issue by Jack-in-42Tokyo** [Shuta-syd/42-ft_transcendence#284]
## 機能概要

![Screen Shot 2023-04-24 at 1 34 11](https://user-images.githubusercontent.com/94432194/233852375-0b42c6b7-ef0a-4294-a24e-75f54a68bfbd.png)

名前が Invite your friendがコンフリクトしている

**Comment by public-jun** [comment]
別にやらなくても良いかも
