### ISSUE TITLE
[game] /game/game_roomに入るとplayer2.name undefindedになるエラー

### ISSUE THREAD

**Issue by Shuta-syd** [Shuta-syd/42-ft_transcendence#340]
フロント側でしっかり取得できないのがエラー原因の可能性高い

<img width="770" alt="Screenshot 2023-05-02 at 15 33 12" src="https://user-images.githubusercontent.com/98635404/235596385-ffbef098-1080-42fc-b9d7-ecac645a4775.png">

**Comment by Jack-in-42Tokyo** [comment]
Errorが起きる時のパターンとしては2人ユーザーがいて、ルームが異なっている時に起きている可能性が高い
